### ISSUE TITLE
Sending an empty body will bypass the validation

### ISSUE THREAD

**Issue by Alexandre-Fernandez** [sfmok/request-input-bundle#10] opened 2023-02-21 14:07 UTC
Sending a POST request with an empty body will bypass the validation and still call the controller, even if your DTO has `#[Assert\NotBlank]` decorators. This is counter intuitive and can lead to bugs since the controller is expecting a filled DTO.

**Comment by sfmok** [comment] 2023-02-21 18:55
I'm going to reproduce and push a fix soon. Thanks, @Alexandre-Fernandez to report it.

**Comment by sfmok** [comment] 2023-02-21 20:04
@Alexandre-Fernandez I couldn't reproduce this issue. If you could provide me with these details that would be great

PHP version
RequestInputBundle version
Request ContentType
A snippet code of invocable or action controller

Meanwhile, I can see 4 ways to bypass resolving and validating the input argument:
RequestInputBundle is disabled (it's enabled by default)
skip_validation config option is enabled  (it's disabled by default)
the input DTO class not implemented the interface "InputInterface"
the request content type is not one of the supported formats "application/json, application/xml, multipart/form-data"

**Comment by Alexandre-Fernandez** [comment] 2023-02-22 13:16
I tried making a [reproduction repository](https://github.com/Alexandre-Fernandez/request-input-bundle-issue-10) and after further testing it seems that this only happens when the `Content-Type` header is missing.
If possible it would be nice to still have an error for this such as `["title" => "Deserialization Failed", "detail" => "Wrong format"]`.

**Comment by sfmok** [comment] 2023-02-23 19:39
Thanks @Alexandre-Fernandez, You're right this is actually a bug. I will fix it and release a patch soon

**Comment by sfmok** [comment] 2023-02-26 13:04
Issue fixed.

throw UnsupportedMediaTypeHttpException in case Content-Type header is missing or unsupported.

**Closed by sfmok** 2023-02-26 13:04 UTC
Labels: bug

**Comment by Alexandre-Fernandez** [comment] 2023-02-26 22:41
great thanks
